-- Crear las tablas base primero (sin dependencias)

-- Tabla de Compañías
CREATE TABLE MES_COMPANIES (
    COMPANY_ID SERIAL PRIMARY KEY,
    NAME TEXT,
    DESCRIPTION TEXT,
    ENABLED_FLAG CHAR(1)
);

-- Tabla de Usuarios
CREATE TABLE MES_USERS (
    USER_ID SERIAL PRIMARY KEY,
    ROLE TEXT,
    NAME TEXT,
    TYPE TEXT,
    PASSWORD TEXT,
    EMAIL TEXT,
    LEVEL SMALLINT,
    RFID INTEGER,
    ENABLED_FLAG CHAR(1)
);

-- Tabla de Fallas
CREATE TABLE MES_FAILURES (
    FAILURE_ID SERIAL PRIMARY KEY,
    NAME TEXT,
    TYPE TEXT
);

-- Crear tablas con dependencias de primer nivel

-- Tabla de Configuraciones
CREATE TABLE MES_SETTINGS (
    SETTING_ID SERIAL PRIMARY KEY,
    COMPANY_ID INTEGER,
    NAME TEXT,
    VALUE TEXT,
    DESCRIPTION TEXT,
    TYPE TEXT,
    STATUS TEXT,
    ENABLED_FLAG CHAR(1),
    CREATED_BY TEXT,
    CREATED_DATE TIMESTAMPTZ,
    UPDATED_BY TEXT,
    UPDATED_DATE TIMESTAMPTZ,
    CONSTRAINT FK_SETTINGS_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES MES_COMPANIES(COMPANY_ID)
);

-- Tabla de Organizaciones
CREATE TABLE MES_ORGANIZATIONS (
    ORGANIZATION_ID SERIAL PRIMARY KEY,
    COMPANY_ID INTEGER,
    CODE TEXT,
    NAME TEXT,
    LOCATION TEXT,
    WORK_METHOD TEXT,
    BU_ID BIGINT,
    COORDINATES TEXT,
    CONSTRAINT FK_ORGANIZATIONS_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES MES_COMPANIES(COMPANY_ID)
);

-- Tabla de Items
CREATE TABLE MES_ITEMS (
    ITEM_ID BIGSERIAL PRIMARY KEY,
    COMPANY_ID INTEGER,
    NUMBER TEXT,
    DESCRIPTION TEXT,
    UOM TEXT,
    TYPE TEXT,
    LOT_CONTROL CHAR(1),
    CONSTRAINT FK_ITEMS_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES MES_COMPANIES(COMPANY_ID)
);

-- Tabla de Dashboards Group
CREATE TABLE MES_DASHBOARDS_GROUP (
  DASHBOARD_GROUP_ID SERIAL PRIMARY KEY,
  ORGANIZATION_ID INTEGER NOT NULL,
  NAME TEXT NOT NULL,
  DESCRIPTION TEXT,
  CREATED_BY INTEGER,
  CREATED_DATE TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  INDEX INTEGER,
  CONSTRAINT FK_DASHBOARDS_GROUP_ORGANIZATION FOREIGN KEY (ORGANIZATION_ID) REFERENCES MES_ORGANIZATIONS(ORGANIZATION_ID)
);

-- Tabla de Dashboards
CREATE TABLE MES_DASHBOARDS (
    DASHBOARD_ID SERIAL PRIMARY KEY,
    DASHBOARD_GROUP_ID INTEGER,
    INDEX INTEGER,
    COL_SIZE INTEGER,
    DATE_RANGE TEXT,
    NAME TEXT,
    COLOR TEXT,
    PARAMETERS JSONB,
    CREATED_DATE TIMESTAMPTZ,
    CREATED_BY TEXT,
    UPDATED_DATE TIMESTAMPTZ,
    UPDATED_BY TEXT,
    CONSTRAINT FK_DASHBOARDS_DASHBOARDS_GROUP FOREIGN KEY (DASHBOARD_GROUP_ID) REFERENCES MES_DASHBOARDS_GROUP(DASHBOARD_GROUP_ID)
);

-- Crear tablas con dependencias de segundo nivel

-- Tabla de Turnos
CREATE TABLE MES_SHIFTS (
    SHIFT_ID SERIAL PRIMARY KEY,
    ORGANIZATION_ID INTEGER,
    NAME TEXT,
    START_TIME TEXT,
    END_TIME TEXT,
    DURATION SMALLINT,
    ENABLED_FLAG CHAR(1),
    CONSTRAINT FK_SHIFTS_ORGANIZATION FOREIGN KEY (ORGANIZATION_ID) REFERENCES MES_ORGANIZATIONS(ORGANIZATION_ID)
);

-- Tabla de Relación Usuarios-Organizaciones
CREATE TABLE MES_USERS_ORG (
    USER_ORG_ID SERIAL PRIMARY KEY,
    USER_ID INTEGER,
    ORGANIZATION_ID INTEGER,
    CONSTRAINT FK_USERS_ORG_USER FOREIGN KEY (USER_ID) REFERENCES MES_USERS(USER_ID),
    CONSTRAINT FK_USERS_ORG_ORGANIZATION FOREIGN KEY (ORGANIZATION_ID) REFERENCES MES_ORGANIZATIONS(ORGANIZATION_ID)
);

-- Tabla de Recursos
CREATE TABLE MES_RESOURCES (
    RESOURCE_ID SERIAL PRIMARY KEY,
    ORGANIZATION_ID INTEGER,
    CODE TEXT,
    NAME TEXT,
    TYPE TEXT,
    CLASS TEXT,
    CONSTRAINT FK_RESOURCES_ORGANIZATION FOREIGN KEY (ORGANIZATION_ID) REFERENCES MES_ORGANIZATIONS(ORGANIZATION_ID)
);

-- Tabla de Máquinas
CREATE TABLE MES_MACHINES (
    MACHINE_ID SERIAL PRIMARY KEY,
    ORGANIZATION_ID INTEGER,
    CODE TEXT,
    NAME TEXT,
    WORK_CENTER_ID BIGINT,
    WORK_CENTER TEXT,
    CLASS TEXT,
    TOKEN TEXT,
    CONSTRAINT FK_MACHINES_ORGANIZATION FOREIGN KEY (ORGANIZATION_ID) REFERENCES MES_ORGANIZATIONS(ORGANIZATION_ID)
);

-- Tabla de Alertas
CREATE TABLE MES_ALERTS (
    ALERT_ID BIGSERIAL PRIMARY KEY,
    MACHINE_ID INTEGER,
    FAILURE_ID INTEGER,
    STATUS TEXT,
    START_DATE TIMESTAMPTZ,
    END_DATE TIMESTAMPTZ,
    RESPONSE_TIME TIMESTAMPTZ,
    REPAIR_TIME TIMESTAMPTZ,
    CONSTRAINT FK_ALERTS_MACHINE FOREIGN KEY (MACHINE_ID) REFERENCES MES_MACHINES(MACHINE_ID),
    CONSTRAINT FK_ALERTS_FAILURE FOREIGN KEY (FAILURE_ID) REFERENCES MES_FAILURES(FAILURE_ID)
);

-- Tabla de Órdenes de Trabajo
CREATE TABLE MES_WORK_ORDERS (
    WORK_ORDER_ID BIGSERIAL PRIMARY KEY,
    ORGANIZATION_ID INTEGER,
    MACHINE_ID INTEGER,
    ITEM_ID BIGINT,
    WORK_DEFINITION_ID BIGINT,
    WORK_ORDER_NUMBER TEXT,
    PLANNED_QUANTITY NUMERIC,
    COMPLETED_QUANTITY NUMERIC,
    STATUS TEXT,
    START_DATE TIMESTAMPTZ,
    END_DATE TIMESTAMPTZ,
    TYPE CHAR(1),
    CONSTRAINT FK_WORK_ORDERS_ORGANIZATION FOREIGN KEY (ORGANIZATION_ID) REFERENCES MES_ORGANIZATIONS(ORGANIZATION_ID),
    CONSTRAINT FK_WORK_ORDERS_MACHINE FOREIGN KEY (MACHINE_ID) REFERENCES MES_MACHINES(MACHINE_ID),
    CONSTRAINT FK_WORK_ORDERS_ITEM FOREIGN KEY (ITEM_ID) REFERENCES MES_ITEMS(ITEM_ID)
);

-- Tabla de Sensores
CREATE TABLE MES_SENSORS (
    SENSOR_ID SERIAL PRIMARY KEY,
    NAME TEXT,
    VAR TEXT,
    ICON TEXT,
    MACHINE_ID INTEGER,
    CREATED_DATE TIMESTAMPTZ,
    CREATED_BY TEXT,
    UPDATED_DATE TIMESTAMPTZ,
    UPDATED_BY TEXT,
    CONSTRAINT FK_SENSORS_MACHINE FOREIGN KEY (MACHINE_ID) REFERENCES MES_MACHINES(MACHINE_ID)
);

-- Crear tablas con dependencias de cuarto nivel

-- Tabla de Ejecución de Trabajo
CREATE TABLE MES_WORK_EXECUTION (
    WORK_EXECUTION_ID BIGSERIAL PRIMARY KEY,
    WORK_ORDER_ID BIGINT,
    EXECUTION_DATE TIMESTAMPTZ,
    SHIFT TEXT,
    READY NUMERIC,
    SCRAP NUMERIC,
    REJECT NUMERIC,
    TARE NUMERIC,
    CONTAINER NUMERIC,
    CONSTRAINT FK_WORK_EXECUTION_WORK_ORDER FOREIGN KEY (WORK_ORDER_ID) REFERENCES MES_WORK_ORDERS(WORK_ORDER_ID)
);

-- Tabla de Despacho de Trabajo
CREATE TABLE MES_WORK_DISPATCH (
    WORK_DISPATCH_ID BIGSERIAL PRIMARY KEY,
    WORK_ORDER_ID BIGINT,
    ITEM_ID BIGINT,
    LOT TEXT,
    OPERATION_ID BIGINT,
    OPERATION_SEQUENCE SMALLINT,
    QUANTITY INTEGER,
    UOM TEXT,
    SUBINVENTORY TEXT,
    ORGNIZATION_ID INTEGER,
    TYPE TEXT,
    CONSTRAINT FK_WORK_DISPATCH_WORK_ORDER FOREIGN KEY (WORK_ORDER_ID) REFERENCES MES_WORK_ORDERS(WORK_ORDER_ID)
);

-- Tabla de KPIs
CREATE TABLE MES_KPIS (
    KPI_ID BIGSERIAL PRIMARY KEY,
    MACHINE_ID INTEGER,
    WORK_ORDER_ID BIGINT,
    KPI_DATE TIMESTAMPTZ,
    AVAILABILITY NUMERIC,
    PEROFORMANCE NUMERIC,
    QUALITY NUMERIC,
    ME NUMERIC,
    MTTA NUMERIC,
    MTBF NUMERIC,
    MTTR NUMERIC,
    CONSTRAINT FK_KPIS_MACHINE FOREIGN KEY (MACHINE_ID) REFERENCES MES_MACHINES(MACHINE_ID),
    CONSTRAINT FK_KPIS_WORK_ORDER FOREIGN KEY (WORK_ORDER_ID) REFERENCES MES_WORK_ORDERS(WORK_ORDER_ID)
);

-- Tabla de Datos de Sensores
CREATE TABLE MES_SENSOR_DATA (
    SENSOR_DATA_ID BIGSERIAL PRIMARY KEY,
    SENSOR_ID INTEGER,
    VALUE NUMERIC,
    COMMENT TEXT,
    DATE_TIME TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SENSOR_DATA_SENSOR FOREIGN KEY (SENSOR_ID) REFERENCES MES_SENSORS(SENSOR_ID)
);

-- Crear índices para mejorar el rendimiento
CREATE INDEX idx_settings_company ON MES_SETTINGS(COMPANY_ID);
CREATE INDEX idx_organizations_company ON MES_ORGANIZATIONS(COMPANY_ID);
CREATE INDEX idx_items_company ON MES_ITEMS(COMPANY_ID);
CREATE INDEX idx_shifts_organization ON MES_SHIFTS(ORGANIZATION_ID);
CREATE INDEX idx_users_org_user ON MES_USERS_ORG(USER_ID);
CREATE INDEX idx_users_org_organization ON MES_USERS_ORG(ORGANIZATION_ID);
CREATE INDEX idx_resources_organization ON MES_RESOURCES(ORGANIZATION_ID);
CREATE INDEX idx_machines_organization ON MES_MACHINES(ORGANIZATION_ID);
--CREATE INDEX idx_users_machines_user ON MES_USERS_MACHINES(USER_ID);
--CREATE INDEX idx_users_machines_machine ON MES_USERS_MACHINES(MACHINE_ID);
CREATE INDEX idx_alerts_machine ON MES_ALERTS(MACHINE_ID);
CREATE INDEX idx_alerts_failure ON MES_ALERTS(FAILURE_ID);
CREATE INDEX idx_work_orders_organization ON MES_WORK_ORDERS(ORGANIZATION_ID);
CREATE INDEX idx_work_orders_machine ON MES_WORK_ORDERS(MACHINE_ID);
CREATE INDEX idx_work_orders_item ON MES_WORK_ORDERS(ITEM_ID);
CREATE INDEX idx_work_execution_work_order ON MES_WORK_EXECUTION(WORK_ORDER_ID);
CREATE INDEX idx_work_dispatch_work_order ON MES_WORK_DISPATCH(WORK_ORDER_ID);
CREATE INDEX idx_kpis_machine ON MES_KPIS(MACHINE_ID);
CREATE INDEX idx_kpis_work_order ON MES_KPIS(WORK_ORDER_ID);
CREATE INDEX idx_sensors_machine ON MES_SENSORS(MACHINE_ID);
CREATE INDEX idx_sensor_data_sensor ON MES_SENSOR_DATA(SENSOR_ID);
--CREATE INDEX idx_dashboards_user ON MES_DASHBOARDS(USER_ID);